//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandromic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corporate
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string Description { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string Code { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
        public string City { get; set; }
        public string Provience { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public Nullable<bool> HeadCenter { get; set; }
    }
}
