//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandromic.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string DigitSign { get; set; }
        public Nullable<System.DateTime> EmpDate { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public string Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public long CorporateId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> EmailIsVerified { get; set; }
        public Nullable<System.DateTime> EmailVerifyDate { get; set; }
        public string EmailVerifyKey { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string SignatureImage { get; set; }
        public decimal FirstUserReg { get; set; }
        public string FirstDateReg { get; set; }
        public Nullable<bool> CanWorkAsSupervisor { get; set; }
        public string IP { get; set; }
        public string ClientName { get; set; }
        public string Phone { get; set; }
    }
}
